/**
 * The GuessingGame class is a class that allows the game to function for the user to be able
 * to guess a number that is generated by the Game class.
 * author: Fares Abdelhamed
 * version: 1
 */
import java.util.InputMismatchException;
import java.util.Scanner;

public class GuessTheNumber {
    /**
    * This main method creates a Game object game based off of the game class,
    * It will continuously loop over, prompting the user to guess the number between 
    * the randomized number values.
    * If the user guesses the value correctly in 4 or lesss attempts, they will be
    * congratulated for their success.
    * Once the user guesses the value correctly, they will be told how many attempts
    * it took for them to guess.
    *
    * @param args the command-line arguments
    */
    public static void main(String[] args) {
        // Creates a new Game object.
        Game game = new Game();

        // Asks the user to guess a number between randomized values.
        Scanner scanner = new Scanner(System.in);
        System.out.println("Guess the number between " + game.getMinNumber() + " and " + game.getMaxNumber() + ".");

        // Loops Prompt of the Game Message
        while (!game.isOver()) {
            try {
                int guess = scanner.nextInt();
                game.guess(guess);
                System.out.println(game.getMessage());
            } catch (InputMismatchException e) {
                System.out.println("Invalid input. Please enter a valid number.");
                scanner.nextLine(); // Clear the invalid input from the scanner
            }
        }
        // If User answers correctly 3 or less attempts, prompted with congratulations.
        if(game.getAttempts()<=3){
            System.out.println("You have guessed the answer in 3 or less attempts. Congrats!");

        }
        else {
            // Tells the user the amount of attempts they have taken to guess correctly.
            System.out.println("You guessed the number in " + game.getAttempts() + " attempts.");
        }
    }
}